

    mov dptr,#resetwatchdog_reload_counter_1_start
    mov dptr,#resetwatchdog_reload_counter_1_end
    mov dptr,#resetwatchdog_reload_counter_2_start
    mov dptr,#resetwatchdog_reload_counter_2_end
    mov dptr,#resetwatchdog_reboot_on_timeout_start
    mov dptr,#resetwatchdog_reboot_on_timeout_end
    mov dptr,#resetwatchdog_on_success_start
    mov dptr,#resetwatchdog_on_success_end
    mov dptr,#resetwatchdog_on_error_start
    mov dptr,#resetwatchdog_on_error_end
